components/CategoryLink.tsx
components/FooterContent.tsx
components/Link.tsx
components/pages/HomePage/AuthorView.tsx
components/pages/HomePage/LeftSection.tsx
components/pages/HomePage/LinkToArticle.tsx
components/pages/HomePage/TopSection.tsx
components/pages/HomePage/index.tsx
pages/_app.tsx
pages/_document.js

This will help us integrate this with Ezoic.

Use new Link component to cause a page refresh on page navigation

---

components/ArticlesView.tsx
components/FooterContent.tsx
pages/_app.tsx

Fix errors such as duplicate `key` and no `className` for `View`.

Fix console errors

---

components/ArticlesView.tsx
components/pages/HomePage/MoreFromTheDailySection.tsx

Revert cartoons changes

---

helpers/constants.ts

Reverts TheStanfordDaily/stanforddaily#50

Revert "Update constants.ts"

---

components/pages/HomePage/index.tsx

Reverts TheStanfordDaily/stanforddaily#52

Revert "Rename "Untitled" tab to "Home""

---

components/ArticlesView.tsx

Reverts TheStanfordDaily/stanforddaily#65

Revert "Hide retractions from homepage"

---

package.json
yarn.lock

Reverts TheStanfordDaily/stanforddaily#74

Revert "Bump next from 9.0.3 to 9.3.2"

---

helpers/wpapi.ts
package.json
yarn.lock

use PT, not UTC, for dates

---

components/pages/HomePage/index.tsx

Remove sponsored content section

---

components/ArticlesView.tsx
components/pages/ArchivePage/index.tsx
components/pages/SearchArchivePage.tsx

Enlarge first article only on category pages

---

components/ContentView.tsx
components/FooterDonationBanner.tsx
components/pages/ArticlePage/index.tsx

Add a donation form under each article. Resolve #33

Add Donation Form

---

components/CategoryList.tsx

Add "voting members" to header

---

components/DonationForm.tsx

Fix default donation amount from $5 to $50

---

components/FooterDonationBanner.tsx

Adds social media tags (facebook, instagram, twitter, youtube) + email signup to footer donation banner on articles.

Added social media and email sign up links to donation footer

---

pages/_app.tsx

Add banner, remove donation header and reader survey

---

components/pages/HomePage/TopSection.tsx

Reverts TheStanfordDaily/stanforddaily#135

Revert "Formatting ads for high school programs & Adopt a Small Business on mobile homepage"

---

components/pages/HomePage/CovidDataWidget.tsx
components/pages/HomePage/index.tsx

[Please describe them here]
[If this is related to existing tickets, include links to them as well ("fixes #[issue number]")]
[If this is a visual change, please add screenshots showing how the website looks like]
[Desktop screenshot]
[Mobile screenshot]

COVID-19 data homepage widget hard-coded v1

---

components/DonationForm.tsx
components/FooterContent.tsx
components/FooterDonationBanner.tsx
components/pages/HomePage/TopSection.tsx
helpers/constants.ts

Also updated Amazon Smile sentence in footer to link '/donate/' page
(See commits below for more details)
Improving presentation of site and promoting new '/donate/' page

Updated tablet breakpoint; restyled donation, top section, 'while you're here' buttons and more

---

components/DonationForm.tsx

Want to promote this competition more since it is timely
**BEFORE**
**AFTER**

Temporarily replace donation banner with Ink Bowl donation contest banner

---

components/ArticlesView.tsx
components/CategoryLink.tsx
components/ContentView.tsx
components/DataVizGlobal.tsx
components/SatireGlobal.tsx
components/TopBarLinks.tsx
components/pages/CategoryArticleListPage.tsx
components/pages/HomePage/SatireSection.tsx
components/pages/HomePage/SectionTitle.tsx
components/pages/HomePage/TextOnlyArticle.tsx
components/pages/HomePage/index.tsx
helpers/wpapi.ts

[Please describe them here]
[If this is related to existing tickets, include links to them as well ("fixes #[issue number]")]
[If this is a visual change, please add screenshots showing how the website looks like]
[Desktop screenshot]
[Mobile screenshot]

Changed all instances of 'satire' to 'humor'

---

pages/_redirect.tsx
pages/for-editors.tsx
pages/for-masthead.tsx
pages/for-staff.tsx
pages/historical.tsx
pages/join-the-daily.tsx
pages/notion.tsx
pages/projects.tsx

[Please describe them here]
[If this is related to existing tickets, include links to them as well ("fixes #[issue number]")]
[If this is a visual change, please add screenshots showing how the website looks like]
[Desktop screenshot]
[Mobile screenshot]

Added redirects for Notion and join-the-daily

---

.github/workflows/build.yml

It's good to end with a newline, right?

Add newline to build.yml

---

pages/_app.tsx

Makes it look better on the site by changing color to daily colors and also position to always bottom right.
fixes #191 
[If this is a visual change, please add screenshots showing how the website looks like]
[Desktop screenshot]

Added custom parameters for accessibility button

---

components/ContentView.tsx

Fixed double parsely script on contentview
